id = "greycat"
name = "GreyCat"
version = "0.1.6"
schema_version = 1
authors = ["maxleiko", "datathings"]
description = "GreyCat support."
repository = "https://github.com/maxleiko/zed-greycat-extension"

[grammars.greycat]
repository = "https://github.com/maxleiko/tree-sitter-greycat"
commit = "aba812d5b3141ff52e5d7f0e95fd437ed1d2e3f5"

[language_servers.greycat]
name = "GreyCat Language Server"
languages = ["GreyCat"]
