id = "greycat"
name = "GreyCat"
version = "0.1.4"
schema_version = 1
authors = ["maxleiko", "datathings"]
description = "GreyCat support."
repository = "https://github.com/maxleiko/zed-greycat-extension"

[grammars.greycat]
repository = "https://github.com/maxleiko/tree-sitter-greycat"
commit = "6e55f6e56366412fef45374c02513db4cac426e2"

[language_servers.greycat]
name = "GreyCat Language Server"
languages = ["GreyCat"]
