id = "greycat"
name = "GreyCat"
version = "0.1.4"
schema_version = 1
authors = ["maxleiko", "datathings"]
description = "GreyCat support."
repository = "https://github.com/maxleiko/zed-greycat-extension"

[grammars.greycat]
repository = "https://github.com/maxleiko/tree-sitter-greycat"
commit = "4ccc09bd4e2d9f0ebb2ad0e1cc926ea2b6db8dd0"

[language_servers.greycat]
name = "GreyCat Language Server"
languages = ["GreyCat"]
